### ISSUE TITLE
"interface" Keyword

### ISSUE THREAD

**Issue by MggMuggins** [ysgard/d-struct#13]
Not sure if it's intentional or not, but the ```interface``` keyword is highlighted yellow instead of purple. The syntax behavior for github's markdown is much more similar to what I would expect.
```D
interface Test {
  void something();
}

class TestClass : Test {
  import std.stdio : writeln;
  void something() {
    writeln("Some stuff");
  }
}
```

**Comment by ysgard** [comment]
Not intentional, and fixed.  Thanks for pointing that out!
