### ISSUE TITLE
Clean up package and convert to ES6

### ISSUE THREAD

**Issue by ysgard** [ysgard/d-struct#14]
Current Atom/package development doesn't use CoffeeScript anymore, but ES6.  I should clean up & convert now while it's still easy.

**Comment by MggMuggins** [comment]
Honestly, if you do JS right, I think it'll probably be more readable than the coffeescript. I think Atom also has support for TypseScript, but I'm not sure you want to get into that.

**Comment by ysgard** [comment]
Not banging on CoffeeScript, which I think was great for handling ES5, but ES6 resolves many of the issues CoffeeScript was designed to paper over.  And I'd rather code in native ES6, as (especially for a beginner like me) converting to and from ES6 examples is overhead I don't need.

**Comment by MggMuggins** [comment]
Yeah. Although some samples _are_ provided in CS instead of JS. Also, cson is (personally) and improvement over json, on a syntactic level.

**Comment by ysgard** [comment]
Closed by #17 
I'll keep the grammar cson, as there's little benefit to converting it at this point.
